cmake_minimum_required(VERSION 3.16)
project(SecureTransfer CXX)
set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
find_package(OpenSSL REQUIRED)
find_package(Threads REQUIRED)
include_directories(include)
add_executable(sft src/main.cpp src/server.cpp src/client.cpp)
target_link_libraries(sft OpenSSL::SSL OpenSSL::Crypto Threads::Threads)
